"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.runRuntimeMcpServer = exports.startLiveDashboardServer = exports.writeDashboardSnapshotFiles = exports.renderDashboardSnapshotMarkdown = exports.SIX_MENTAL_MODEL_ORDER = exports.FORBIDDEN_COMPLETION_SOURCES = exports.buildSixMentalModelProjection = exports.queryRuntimeDashboard = exports.buildRuntimeDashboardModel = exports.formatDashboardMarkdown = exports.getEpicDimensionScores = exports.computeEpicHealthScore = exports.getEpicAggregateRecords = exports.aggregateByEpicOnly = exports.aggregateByEpicStoryTimeWindow = exports.getTrend = exports.countVetoTriggers = exports.getHighIterationTop3 = exports.getGovernanceRerunGateFailureTrend = exports.getGovernanceSignalHotspots = exports.getGovernanceRoutingModeDistribution = exports.getGovernanceRoutingSummary = exports.getJourneyContractSummary = exports.getWeakTop3EpicStory = exports.getWeakTop3 = exports.getDimensionScores = exports.computeHealthScore = exports.getRecentRuns = exports.getLatestRunRecordsV2 = exports.getLatestRunRecords = exports.groupByRunId = void 0;
/**
 * Story 7.1: 仪表盘生成模块
 */
var compute_1 = require("./compute");
Object.defineProperty(exports, "groupByRunId", { enumerable: true, get: function () { return compute_1.groupByRunId; } });
Object.defineProperty(exports, "getLatestRunRecords", { enumerable: true, get: function () { return compute_1.getLatestRunRecords; } });
Object.defineProperty(exports, "getLatestRunRecordsV2", { enumerable: true, get: function () { return compute_1.getLatestRunRecordsV2; } });
Object.defineProperty(exports, "getRecentRuns", { enumerable: true, get: function () { return compute_1.getRecentRuns; } });
Object.defineProperty(exports, "computeHealthScore", { enumerable: true, get: function () { return compute_1.computeHealthScore; } });
Object.defineProperty(exports, "getDimensionScores", { enumerable: true, get: function () { return compute_1.getDimensionScores; } });
Object.defineProperty(exports, "getWeakTop3", { enumerable: true, get: function () { return compute_1.getWeakTop3; } });
Object.defineProperty(exports, "getWeakTop3EpicStory", { enumerable: true, get: function () { return compute_1.getWeakTop3EpicStory; } });
Object.defineProperty(exports, "getJourneyContractSummary", { enumerable: true, get: function () { return compute_1.getJourneyContractSummary; } });
Object.defineProperty(exports, "getGovernanceRoutingSummary", { enumerable: true, get: function () { return compute_1.getGovernanceRoutingSummary; } });
Object.defineProperty(exports, "getGovernanceRoutingModeDistribution", { enumerable: true, get: function () { return compute_1.getGovernanceRoutingModeDistribution; } });
Object.defineProperty(exports, "getGovernanceSignalHotspots", { enumerable: true, get: function () { return compute_1.getGovernanceSignalHotspots; } });
Object.defineProperty(exports, "getGovernanceRerunGateFailureTrend", { enumerable: true, get: function () { return compute_1.getGovernanceRerunGateFailureTrend; } });
Object.defineProperty(exports, "getHighIterationTop3", { enumerable: true, get: function () { return compute_1.getHighIterationTop3; } });
Object.defineProperty(exports, "countVetoTriggers", { enumerable: true, get: function () { return compute_1.countVetoTriggers; } });
Object.defineProperty(exports, "getTrend", { enumerable: true, get: function () { return compute_1.getTrend; } });
Object.defineProperty(exports, "aggregateByEpicStoryTimeWindow", { enumerable: true, get: function () { return compute_1.aggregateByEpicStoryTimeWindow; } });
Object.defineProperty(exports, "aggregateByEpicOnly", { enumerable: true, get: function () { return compute_1.aggregateByEpicOnly; } });
Object.defineProperty(exports, "getEpicAggregateRecords", { enumerable: true, get: function () { return compute_1.getEpicAggregateRecords; } });
Object.defineProperty(exports, "computeEpicHealthScore", { enumerable: true, get: function () { return compute_1.computeEpicHealthScore; } });
Object.defineProperty(exports, "getEpicDimensionScores", { enumerable: true, get: function () { return compute_1.getEpicDimensionScores; } });
var format_1 = require("./format");
Object.defineProperty(exports, "formatDashboardMarkdown", { enumerable: true, get: function () { return format_1.formatDashboardMarkdown; } });
var runtime_query_1 = require("./runtime-query");
Object.defineProperty(exports, "buildRuntimeDashboardModel", { enumerable: true, get: function () { return runtime_query_1.buildRuntimeDashboardModel; } });
Object.defineProperty(exports, "queryRuntimeDashboard", { enumerable: true, get: function () { return runtime_query_1.queryRuntimeDashboard; } });
var six_model_projection_1 = require("./six-model-projection");
Object.defineProperty(exports, "buildSixMentalModelProjection", { enumerable: true, get: function () { return six_model_projection_1.buildSixMentalModelProjection; } });
Object.defineProperty(exports, "FORBIDDEN_COMPLETION_SOURCES", { enumerable: true, get: function () { return six_model_projection_1.FORBIDDEN_COMPLETION_SOURCES; } });
Object.defineProperty(exports, "SIX_MENTAL_MODEL_ORDER", { enumerable: true, get: function () { return six_model_projection_1.SIX_MENTAL_MODEL_ORDER; } });
var snapshot_1 = require("./snapshot");
Object.defineProperty(exports, "renderDashboardSnapshotMarkdown", { enumerable: true, get: function () { return snapshot_1.renderDashboardSnapshotMarkdown; } });
Object.defineProperty(exports, "writeDashboardSnapshotFiles", { enumerable: true, get: function () { return snapshot_1.writeDashboardSnapshotFiles; } });
var live_server_1 = require("./live-server");
Object.defineProperty(exports, "startLiveDashboardServer", { enumerable: true, get: function () { return live_server_1.startLiveDashboardServer; } });
var mcp_server_1 = require("./mcp-server");
Object.defineProperty(exports, "runRuntimeMcpServer", { enumerable: true, get: function () { return mcp_server_1.runRuntimeMcpServer; } });
