import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { sha256Stable } from '../scripts/requirements-contract-semantic-resolver';
import { REQUIREMENTS_CONTRACT_VALIDATION_FACADE_ID } from '../scripts/requirements-contract-validation-facade';

export const REQUIREMENTS_CONTRACT_CANONICAL_ASSETS_VALIDATION_FACADE =
  REQUIREMENTS_CONTRACT_VALIDATION_FACADE_ID;

export const REQUIREMENTS_CONTRACT_CANONICAL_ASSETS_MANIFEST_OWNER_PATH =
  'packages/bmad-speckit/src/main-agent/source-authority/rules/requirements-contract-canonical-assets-manifest.ts';

const CANONICAL_ASSETS = [
  {
    assetId: 'semantic_ir_schema',
    version: 'requirement-contract-model/v2',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirement-contract-model-v2.schema.json',
    role: 'typed_semantic_ir_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'canonical_markdown_parser',
    version: 'requirements-contract-markdown-source-parser/v1',
    path: '_bmad/shared/requirements-contract/markdown-source-parser.js',
    role: 'canonical_parser',
    assetKind: 'parser',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'validation_rule_registry',
    version: 'requirements-contract-source-prd-rules/v2',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/rules/requirements-contract-source-prd-rules.ts',
    role: 'validation_rule_registry',
    assetKind: 'registry',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'validation_facade',
    version: 'requirements-contract-validation-facade/v2',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-validation-facade.ts',
    role: 'validation_facade',
    assetKind: 'facade',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'projection_registry',
    version: 'requirements-contract-projection-registry/v1',
    path: '_bmad/shared/requirements-contract/requirements-contract-projection-registry.json',
    role: 'projection_registry',
    assetKind: 'registry',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'consumer_registry',
    version: 'requirements-contract-consumer-registry/v2',
    path: '_bmad/shared/requirements-contract/requirements-contract-consumer-registry.json',
    role: 'consumer_registry',
    assetKind: 'registry',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'discovery_envelope_template',
    version: 'requirements-contract-discovery-prd-envelope-template/v1',
    path: '_bmad/shared/requirements-contract/templates/discovery-prd-envelope-template.md',
    role: 'discovery_envelope_template',
    assetKind: 'template',
    authorityClass: 'none',
  },
  {
    assetId: 'product_prd_template',
    version: 'requirements-contract-product-prd-template/v1',
    path: '_bmad/shared/requirements-contract/templates/product-prd-template.md',
    role: 'product_prd_template',
    assetKind: 'template',
    authorityClass: 'product_background',
  },
  {
    assetId: 'product_prd_renderer',
    version: 'registered-product-prd-renderer/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-prd-render-write-seam.ts',
    role: 'product_prd_renderer',
    assetKind: 'renderer',
    authorityClass: 'product_background',
    symbolRef: 'renderProductPrd',
  },
  {
    assetId: 'source_prd_template',
    version: 'requirements-contract-source-prd-template/v2',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/templates/requirements-contract-source-prd-template.md',
    role: 'source_prd_template',
    assetKind: 'template',
    authorityClass: 'implementation_semantic_authority',
  },
  {
    assetId: 'source_prd_renderer',
    version: 'registered-source-prd-renderer/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-prd-render-write-seam.ts',
    role: 'source_prd_renderer',
    assetKind: 'renderer',
    authorityClass: 'none',
    symbolRef: 'renderCanonicalRequirementSourcePrd',
  },
  {
    assetId: 'implementation_confirmation_schema',
    version: 'requirements-contract-implementation-confirmation/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-implementation-confirmation.schema.json',
    role: 'implementation_confirmation_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'implementation_confirmation_projector',
    version: 'requirements-contract-implementation-confirmation-projector/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-implementation-confirmation-projector.ts',
    role: 'implementation_confirmation_projector',
    assetKind: 'projector',
    authorityClass: 'none',
    symbolRef: 'projectRequirementsContractImplementationConfirmation',
  },
  {
    assetId: 'implementation_confirmation_validator',
    version: 'requirements-contract-implementation-confirmation-validator/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-implementation-confirmation-validator.ts',
    role: 'implementation_confirmation_validator',
    assetKind: 'validator',
    authorityClass: 'deterministic_contract',
    symbolRef: 'validateRequirementsContractImplementationConfirmation',
  },
  {
    assetId: 'implementation_confirmation_codec',
    version: 'requirements-contract-implementation-confirmation-codec/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-implementation-confirmation-codec.ts',
    role: 'implementation_confirmation_codec',
    assetKind: 'codec',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'implementation_confirmation_reference',
    version: 'requirements-contract-implementation-confirmation-reference/v1',
    path: '_bmad/skills/requirements-contract-authoring/references/implementation-confirmation-reference.md',
    role: 'implementation_confirmation_reference',
    assetKind: 'reference',
    authorityClass: 'none',
  },
  {
    assetId: 'confirmation_render_input_schema',
    version: 'requirements-confirmation-render-input/v2',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-confirmation-render-input-v2.schema.json',
    role: 'confirmation_render_input_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'confirmation_render_input_projector',
    version: 'requirements-confirmation-render-input/v2',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-confirmation-render-input.ts',
    role: 'confirmation_render_input_projector',
    assetKind: 'projector',
    authorityClass: 'none',
    symbolRef: 'createRequirementsConfirmationRenderInput',
  },
  {
    assetId: 'confirmation_renderer',
    version: 'requirements-contract-confirmation-html-renderer/v1',
    path: '_bmad/skills/requirements-contract-authoring/scripts/render-requirements-confirmation-html.ts',
    role: 'confirmation_renderer',
    assetKind: 'renderer',
    authorityClass: 'none',
  },
  {
    assetId: 'confirmation_renderer_specification',
    version: 'requirements-contract-confirmation-renderer-specification/v1',
    path: '_bmad/skills/requirements-contract-authoring/references/html-confirmation-renderer-spec.md',
    role: 'confirmation_renderer_specification',
    assetKind: 'reference',
    authorityClass: 'none',
  },
  {
    assetId: 'goal_contract_template',
    version: 'goal-execution-contract-template/v1',
    path: '_bmad/shared/goal-contract/goal-execution-contract-template.md',
    role: 'goal_contract_template',
    assetKind: 'template',
    authorityClass: 'none',
  },
  {
    assetId: 'goal_contract_profile',
    version: 'goal-contract-profile/v1',
    path: '_bmad/shared/goal-contract/goal-contract-profile.json',
    role: 'goal_contract_profile',
    assetKind: 'profile',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_renderer',
    version: 'req-trace-goal-contract-renderer/v1',
    path: '_bmad/shared/goal-contract/scripts/render-goal-contract.js',
    role: 'goal_contract_renderer',
    assetKind: 'renderer',
    authorityClass: 'none',
  },
  {
    assetId: 'goal_contract_partition_methodology_profile',
    version: 'partition-methodology-profile/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-methodology-profile.json',
    role: 'goal_contract_partition_methodology_profile',
    assetKind: 'profile',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_methodology_profile_schema',
    version: 'partition-methodology-profile/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-methodology-profile.schema.json',
    role: 'goal_contract_partition_methodology_profile_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_sequence_applicability_receipt_schema',
    version: 'goal-contract-sequence-applicability-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-sequence-applicability-receipt.schema.json',
    role: 'goal_contract_sequence_applicability_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_semantic_provider_registry',
    version: 'goal-contract-semantic-provider-registry/v1',
    path: '_bmad/shared/goal-contract/goal-contract-semantic-provider-registry.json',
    role: 'goal_contract_semantic_provider_registry',
    assetKind: 'registry',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_semantic_provider_registry_schema',
    version: 'goal-contract-semantic-provider-registry/v1',
    path: '_bmad/shared/goal-contract/goal-contract-semantic-provider-registry.schema.json',
    role: 'goal_contract_semantic_provider_registry_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_execution_projection_schema',
    version: 'goal-contract-execution-projection/v1',
    path: '_bmad/shared/goal-contract/goal-contract-execution-projection.schema.json',
    role: 'goal_contract_execution_projection_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_policy',
    version: 'goal-contract-partition-policy/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-policy.json',
    role: 'goal_contract_partition_policy',
    assetKind: 'profile',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_policy_schema',
    version: 'goal-contract-partition-policy/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-policy.schema.json',
    role: 'goal_contract_partition_policy_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_impact_policy',
    version: 'goal-contract-partition-impact-policy/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-impact-policy.json',
    role: 'goal_contract_partition_impact_policy',
    assetKind: 'profile',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_impact_policy_schema',
    version: 'goal-contract-partition-impact-policy/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-impact-policy.schema.json',
    role: 'goal_contract_partition_impact_policy_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_impact_graph_schema',
    version: 'goal-contract-partition-impact-graph/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-impact-graph.schema.json',
    role: 'goal_contract_partition_impact_graph_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_closure_feasibility_receipt_schema',
    version: 'goal-contract-partition-closure-feasibility-receipt/v1',
    path:
      '_bmad/shared/goal-contract/goal-contract-partition-closure-feasibility-receipt.schema.json',
    role: 'goal_contract_partition_closure_feasibility_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_impact_drift_receipt_schema',
    version: 'goal-contract-partition-impact-drift-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-impact-drift-receipt.schema.json',
    role: 'goal_contract_partition_impact_drift_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_manifest_schema',
    version: 'goal-contract-partition-manifest/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-manifest.schema.json',
    role: 'goal_contract_partition_manifest_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_output_authority_schema',
    version: 'goal-contract-partition-output-authority/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-output-authority.schema.json',
    role: 'goal_contract_partition_output_authority_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_lifecycle_authority_binding_schema',
    version: 'goal-contract-lifecycle-authority-binding/v1',
    path: '_bmad/shared/goal-contract/goal-contract-lifecycle-authority-binding.schema.json',
    role: 'goal_contract_lifecycle_authority_binding_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_analysis_receipt_schema',
    version: 'goal-contract-partition-analysis-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-analysis-receipt.schema.json',
    role: 'goal_contract_partition_analysis_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_global_coverage_receipt_schema',
    version: 'goal-contract-partition-global-coverage-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-global-coverage-receipt.schema.json',
    role: 'goal_contract_partition_global_coverage_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_selection_receipt_schema',
    version: 'goal-contract-partition-selection-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-selection-receipt.schema.json',
    role: 'goal_contract_partition_selection_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_dependency_compatibility_receipt_schema',
    version: 'goal-contract-dependency-compatibility-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-dependency-compatibility-receipt.schema.json',
    role: 'goal_contract_dependency_compatibility_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_child_coverage_receipt_schema',
    version: 'goal-contract-partition-child-coverage-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-child-coverage-receipt.schema.json',
    role: 'goal_contract_partition_child_coverage_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_child_generation_receipt_schema',
    version: 'goal-contract-partition-child-generation-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-child-generation-receipt.schema.json',
    role: 'goal_contract_partition_child_generation_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_plan_schema',
    version: 'goal-contract-partition-plan/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-plan.schema.json',
    role: 'goal_contract_partition_plan_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_authority_supersession_receipt_schema',
    version: 'goal-contract-authority-supersession-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-authority-supersession-receipt.schema.json',
    role: 'goal_contract_authority_supersession_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_source_grounded_coverage_receipt_schema',
    version: 'goal-contract-source-grounded-coverage-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-source-grounded-coverage-receipt.schema.json',
    role: 'goal_contract_source_grounded_coverage_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_partition_release_gate_receipt_schema',
    version: 'goal-contract-partition-release-gate-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-partition-release-gate-receipt.schema.json',
    role: 'goal_contract_partition_release_gate_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_campaign_activation_receipt_schema',
    version: 'goal-contract-campaign-activation-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-campaign-activation-receipt.schema.json',
    role: 'goal_contract_campaign_activation_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_subcontract_execution_lease_schema',
    version: 'goal-contract-subcontract-execution-lease/v1',
    path: '_bmad/shared/goal-contract/goal-contract-subcontract-execution-lease.schema.json',
    role: 'goal_contract_subcontract_execution_lease_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_subcontract_evidence_schema',
    version: 'goal-contract-subcontract-evidence/v1',
    path: '_bmad/shared/goal-contract/goal-contract-subcontract-evidence.schema.json',
    role: 'goal_contract_subcontract_evidence_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_subcontract_closure_receipt_schema',
    version: 'goal-contract-subcontract-closure-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-subcontract-closure-receipt.schema.json',
    role: 'goal_contract_subcontract_closure_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'goal_contract_campaign_closure_receipt_schema',
    version: 'goal-contract-campaign-closure-receipt/v1',
    path: '_bmad/shared/goal-contract/goal-contract-campaign-closure-receipt.schema.json',
    role: 'goal_contract_campaign_closure_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'closeout_packet_schema',
    version: 'requirements-contract-terminal-closeout-packet/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-terminal-closeout-packet.schema.json',
    role: 'closeout_packet_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'closeout_renderer',
    version: 'requirements-contract-terminal-closeout/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-terminal-closeout.ts',
    role: 'closeout_renderer',
    assetKind: 'renderer',
    authorityClass: 'none',
    symbolRef: 'renderRequirementsContractTerminalCloseout',
  },
  {
    assetId: 'closeout_readback_receipt_schema',
    version: 'requirements-contract-artifact-readback-receipt/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-artifact-readback-receipt.schema.json',
    role: 'closeout_readback_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'closeout_final_response_projector',
    version: 'requirements-contract-terminal-closeout-projector/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-terminal-closeout.ts',
    role: 'closeout_final_response_projector',
    assetKind: 'projector',
    authorityClass: 'none',
    symbolRef: 'projectRequirementsContractTerminalCloseout',
  },
  {
    assetId: 'judge_runtime_schema',
    version: 'requirements-contract-judge-runtime/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-runtime.schema.json',
    role: 'judge_runtime_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_credentials_schema',
    version: 'requirements-contract-judge-credentials/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-credentials.schema.json',
    role: 'judge_credentials_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'normalized_judge_response_schema',
    version: 'requirements-contract-normalized-judge-response/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-normalized-judge-response.schema.json',
    role: 'normalized_judge_response_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'cli_judge_execution_receipt_schema',
    version: 'requirements-contract-cli-judge-execution-receipt/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-cli-judge-execution-receipt.schema.json',
    role: 'cli_judge_execution_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_capability_receipt_schema',
    version: 'requirements-contract-judge-capability-receipt/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-capability-receipt.schema.json',
    role: 'judge_capability_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_selection_receipt_schema',
    version: 'requirements-contract-judge-selection-receipt/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-selection-receipt.schema.json',
    role: 'judge_selection_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_provider_registry_schema',
    version: 'requirements-contract-judge-provider-registry/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-provider-registry.schema.json',
    role: 'judge_provider_registry_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_challenge_tests_schema',
    version: 'requirements-contract-judge-challenge-tests/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-challenge-tests.schema.json',
    role: 'judge_challenge_tests_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_response_schema',
    version: 'requirements-contract-judge-response/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-response.schema.json',
    role: 'judge_response_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_runtime_security_parity_schema',
    version: 'requirements-contract-judge-runtime-security-parity/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-runtime-security-parity.schema.json',
    role: 'judge_runtime_security_parity_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_provider_smoke_input_schema',
    version: 'requirements-contract-judge-provider-smoke-input/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-provider-smoke-input.schema.json',
    role: 'judge_provider_smoke_input_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_credential_initialization_input_schema',
    version: 'requirements-contract-judge-credential-initialization-input/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-credential-initialization-input.schema.json',
    role: 'judge_credential_initialization_input_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_credential_initialization_receipt_schema',
    version: 'requirements-contract-judge-credential-initialization-receipt/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-credential-initialization-receipt.schema.json',
    role: 'judge_credential_initialization_receipt_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_audit_unit_projection_input_schema',
    version: 'requirements-contract-judge-audit-unit-projection-input/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-audit-unit-projection-input.schema.json',
    role: 'judge_audit_unit_projection_input_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_audit_unit_set_schema',
    version: 'requirements-contract-judge-audit-unit-set/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-judge-audit-unit-set.schema.json',
    role: 'judge_audit_unit_set_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'gap_closure_readonly_auditor_adapter_input_schema',
    version: 'requirements-contract-gap-closure-readonly-auditor-adapter-input/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-gap-closure-readonly-auditor-adapter-input.schema.json',
    role: 'gap_closure_readonly_auditor_adapter_input_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'gap_closure_independent_audit_request_schema',
    version: 'requirements-contract-gap-closure-independent-audit-request/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-gap-closure-independent-audit-request.schema.json',
    role: 'gap_closure_independent_audit_request_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'gap_closure_independent_audit_assessment_schema',
    version: 'requirements-contract-gap-closure-independent-audit-assessment/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-gap-closure-independent-audit-assessment.schema.json',
    role: 'gap_closure_independent_audit_assessment_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'gap_closure_independent_audit_result_schema',
    version: 'requirements-contract-gap-closure-independent-audit-result/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/schemas/requirements-contract-gap-closure-independent-audit-result.schema.json',
    role: 'gap_closure_independent_audit_result_schema',
    assetKind: 'schema',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'gap_closure_readonly_auditor_adapter',
    version: 'requirements-contract-gap-closure-readonly-auditor-adapter/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-gap-closure-readonly-auditor-adapter.ts',
    role: 'gap_closure_readonly_auditor_adapter',
    assetKind: 'adapter',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'critical_auditor_profile',
    version: 'critical-auditor-profile/v1',
    path: '_bmad/shared/critical-auditor-profile/critical-auditor-profile.json',
    role: 'critical_auditor_profile',
    assetKind: 'profile',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_provider_registry_projection',
    version: 'requirements-contract-judge-provider-registry/v1',
    path: '_bmad/shared/requirements-contract/requirements-contract-judge-provider-registry.json',
    role: 'judge_provider_registry_projection',
    assetKind: 'registry',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_credential_resolver',
    version: 'requirements-contract-judge-credential-resolver/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-judge-credential-resolver.ts',
    role: 'judge_credential_resolver',
    assetKind: 'resolver',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_provider_registry',
    version: 'requirements-contract-judge-provider-registry-runtime/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-judge-provider-registry.ts',
    role: 'judge_provider_registry',
    assetKind: 'registry',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'openai_compatible_judge_adapter',
    version: 'requirements-contract-openai-compatible-judge-adapter/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-openai-compatible-judge-adapter.ts',
    role: 'openai_compatible_judge_adapter',
    assetKind: 'adapter',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'anthropic_compatible_judge_adapter',
    version: 'requirements-contract-anthropic-compatible-judge-adapter/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-anthropic-compatible-judge-adapter.ts',
    role: 'anthropic_compatible_judge_adapter',
    assetKind: 'adapter',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'claude_code_cli_judge_adapter',
    version: 'requirements-contract-claude-code-cli-judge-adapter/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-claude-code-cli-judge-adapter.ts',
    role: 'claude_code_cli_judge_adapter',
    assetKind: 'adapter',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'codex_cli_judge_adapter',
    version: 'requirements-contract-codex-cli-judge-adapter/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-codex-cli-judge-adapter.ts',
    role: 'codex_cli_judge_adapter',
    assetKind: 'adapter',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_provider_smoke',
    version: 'requirements-contract-judge-provider-smoke/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-judge-provider-smoke.ts',
    role: 'judge_provider_smoke',
    assetKind: 'producer',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_credential_initializer',
    version: 'requirements-contract-judge-credential-initializer/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-judge-credential-initializer.ts',
    role: 'judge_credential_initializer',
    assetKind: 'producer',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_audit_unit_projector',
    version: 'requirements-contract-judge-audit-unit-projector/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-judge-audit-unit-projector.ts',
    role: 'judge_audit_unit_projector',
    assetKind: 'producer',
    authorityClass: 'deterministic_contract',
  },
  {
    assetId: 'judge_runtime_bindings_resolver',
    version: 'requirements-contract-judge-runtime-bindings/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-judge-runtime-bindings.ts',
    role: 'judge_runtime_bindings_resolver',
    assetKind: 'resolver',
    authorityClass: 'deterministic_contract',
    symbolRef: 'resolveRequirementsContractJudgeRuntimeBindings',
  },
  {
    assetId: 'reverse_audit_validator',
    version: 'requirements-contract-reverse-audit/v1',
    path: 'packages/bmad-speckit/src/main-agent/source-authority/scripts/requirements-contract-reverse-audit.ts',
    role: 'reverse_audit_validator',
    assetKind: 'validator',
    authorityClass: 'deterministic_contract',
  },
] as const;

function fileHash(root: string, relativePath: string): string {
  const bytes = readFileSync(path.resolve(root, relativePath));
  if (bytes.includes(0x0d)) {
    throw new Error(`requirements_contract_projection_hash_input_not_lf:${relativePath}`);
  }
  return `sha256:${createHash('sha256')
    .update(bytes)
    .digest('hex')}`;
}

export function createRequirementsContractCanonicalAssetsManifest(root = process.cwd()) {
  const schemaVersion = 'requirements-contract-canonical-assets-manifest/v2';
  const assets = CANONICAL_ASSETS.map((asset) => ({
    ...asset,
    sha256: fileHash(root, asset.path),
  }));
  return {
    schemaVersion,
    owner: {
      path: REQUIREMENTS_CONTRACT_CANONICAL_ASSETS_MANIFEST_OWNER_PATH,
      hash: fileHash(root, REQUIREMENTS_CONTRACT_CANONICAL_ASSETS_MANIFEST_OWNER_PATH),
    },
    manifestHash: sha256Stable({ schemaVersion, assets }),
    assets,
    authority: 'none',
  } as const;
}

export const REQUIREMENTS_CONTRACT_CANONICAL_ASSETS = CANONICAL_ASSETS;
